#neutering
neuter = 'Your role is to ANONYMIZE all text that is provided by the user. After you have anonymized a text, NOBODY, not even an expert financial analyst should be able to use the text to identify the company or the industry the company operates in. For example, if the text is: The country’s largest phone producer Apple had great phone-related earnings but Google did not in 2024, likely because of Apple’s slogan Think Different, then you should ANONYMIZE it to: The country’s largest product_type_1 producer Company_1 had great product_type_1 related earnings but Company_2 did not in time_1 likely because of Company_1’s slogan slogan_1. You should also ANONYMIZE any other information which one could use to identify the company or to make an educated guess about its identity. Stock tickers are identifiers, are usually four or fewer capitalized letters (consider TIKR as a stand-in for an arbitrary ticker), and can be referenced in the text in the following formats; SYMBOL:TIKR, $TIKR, >TIKR, $ TIKR, SYMBOL TIKR, SYMBOL: TIKR, > TIKR. Make sure you ANONYMIZE TIKR to ticker_x. Also ANONYMIZE any other identifiers related to companies including the names of individuals, locations, industries, sectors, product names and types and generic product lines, services, times, years, dates and all numbers and percentages in the text, including units. These should be replaced with name_x, location_x, industry_x, sector_x, product_x, product_type_x, product_line_x, service_x, time_x, year_x, date_x and number a, b, c, respectively. Also replace any website or internet links with link_x. You should never just delete an identifier; instead, always replace it with an anonymized analog. After you read and ANONYMIZE the text, you should output the anonymized text and nothing else.'
neuter_start = 'Your role is to ANONYMIZE all text that is provided by the user. '
neuter_start_iter = 'Your role is to ANONYMIZE all text that is provided by the user. You have already tried to anonymize the following text and failed, you left details which were used to identify the text by an expert. Be more agressive in your efforts to anonymize and pay more attention to not leave even the most minute details. '
neuter_name = 'The text you need to anonymize will be about the firm: '
neuter_ticker = 'whose ticker is: '
neuter_industry = 'and is in the industry of: '
neuter_end = 'Any instance of the firm, their products, the industry or industry related areas they are involved in should be anonymized. After you have anonymized a text, NOBODY, not even an expert financial analyst should be able to use the text to identify the company or the industry the company operates in. For example, if the text is: The country’s largest phone producer Apple had great phone-related earnings but Google did not in 2024, likely because of Apple’s slogan Think Different, then you should ANONYMIZE it to: The country’s largest product_type_1 producer Company_1 had great product_type_1 related earnings but Company_2 did not in time_1 likely because of Company_1’s slogan slogan_1. You should also ANONYMIZE any other information which one could use to identify the company or to make an educated guess about its identity. Stock tickers are identifiers, are usually four or fewer capitalized letters (consider TIKR as a stand-in for an arbitrary ticker), and can be referenced in the text in the following formats; SYMBOL:TIKR, $TIKR, >TIKR, $ TIKR, SYMBOL TIKR, SYMBOL: TIKR, > TIKR. Make sure you ANONYMIZE TIKR to ticker_x. Also ANONYMIZE any other identifiers related to companies including the names of individuals, locations, industries, sectors, product names and types and generic product lines, services, times, years, dates and all numbers and percentages in the text, including units. These should be replaced with name_x, location_x, industry_x, sector_x, product_x, product_type_x, product_line_x, service_x, time_x, year_x, date_x and number a, b, c, respectively. Also replace any website or internet links with link_x. You should never just delete an identifier; instead, always replace it with an anonymized analog. After you read and ANONYMIZE the text, you should output the anonymized text and nothing else.'
neuter_end = 'Any instance of the firm, their products, the industry or industry related areas they are involved in should be anonymized. Absolutely no mention of key words related to that industry can be left in the text. After you have anonymized a text, NOBODY, not even an expert financial analyst should be able to use the text to identify the company or the industry the company operates in. For example, if the text is: The country’s largest phone producer Apple had great phone-related earnings but Google did not in 2024, likely because of Apple’s slogan Think Different, then you should ANONYMIZE it to: The country’s largest product_type_1 producer Company_1 had great product_type_1 related earnings but Company_2 did not in time_1 likely because of Company_1’s slogan slogan_1. You should also ANONYMIZE any other information which one could use to identify the company or to make an educated guess about its identity. Stock tickers are identifiers, are usually four or fewer capitalized letters (consider TIKR as a stand-in for an arbitrary ticker), and can be referenced in the text in the following formats; SYMBOL:TIKR, $TIKR, >TIKR, $ TIKR, SYMBOL TIKR, SYMBOL: TIKR, > TIKR. Make sure you ANONYMIZE TIKR to ticker_x. Also ANONYMIZE any other identifiers related to companies including the names of individuals, locations, industries, sectors, product names and types and generic product lines, services, times, years, dates and all numbers and percentages in the text, including units. These should be replaced with name_x, location_x, industry_x, sector_x, product_x, product_type_x, product_line_x, service_x, time_x, year_x, date_x and number a, b, c, respectively. Also replace any website or internet links with link_x. You should never just delete an identifier; instead, always replace it with an anonymized analog. After you read and ANONYMIZE the text, you should output the anonymized text and nothing else.'
neuter_end_iter = 'Any instance of the firm, their products, the industry or industry related areas they are involved in should be anonymized. Absolutely no mention of key words related to that industry can be left in the text. After you have anonymized a text, NOBODY, not even an expert financial analyst should be able to use the text to identify the company or the industry the company operates in. For example, if the text is: The country’s largest phone producer Apple had great phone-related earnings but Google did not in 2024, likely because of Apple’s slogan Think Different, then you should ANONYMIZE it to: The country’s largest product_type_1 producer Company_1 had great product_type_1 related earnings but Company_2 did not in time_1 likely because of Company_1’s slogan slogan_1. You should also ANONYMIZE any other information which one could use to identify the company or to make an educated guess about its identity. Stock tickers are identifiers, are usually four or fewer capitalized letters (consider TIKR as a stand-in for an arbitrary ticker), and can be referenced in the text in the following formats; SYMBOL:TIKR, $TIKR, >TIKR, $ TIKR, SYMBOL TIKR, SYMBOL: TIKR, > TIKR. Make sure you ANONYMIZE TIKR to ticker_x. Also ANONYMIZE any other identifiers related to companies including the names of individuals, locations, industries, sectors, product names and types and generic product lines, services, times, years, dates and all numbers and percentages in the text, including units. These should be replaced with name_x, location_x, industry_x, sector_x, product_x, product_type_x, product_line_x, service_x, time_x, year_x, date_x and number a, b, c, respectively. Also replace any website or internet links with link_x. You should never just delete an identifier; instead, always replace it with an anonymized analog. You have already failed me before, take no chances this time and be aggressive in censoring the text. After you read and ANONYMIZE the text, you should output the anonymized text and nothing else.'

neuter_template = {
    'template': [
        neuter_start,
        {'column': 'COMNAM', 'prefix': neuter_name, 'suffix': ' '},
        {'column': 'Companies', 'prefix': neuter_ticker, 'suffix': ' '},
        {'column': 'SIC_Industry', 'prefix': neuter_industry, 'suffix': '.'},
        neuter_end
    ]
}
neuter_template_iter = {
    'template': [
        neuter_start_iter,
        {'column': 'COMNAM', 'prefix': neuter_name, 'suffix': ' '},
        {'column': 'Companies', 'prefix': neuter_ticker, 'suffix': ' '},
        {'column': 'SIC_Industry', 'prefix': neuter_industry, 'suffix': '.'},
        neuter_end_iter
    ]
}


#neuter_ending = 'After you read and ANONYMIZE the text, you should output the anonymized text and nothing else.'
#neuter_1 = 'Your role is to ANONYMIZE all text that is provided by the user. After you have anonymized a text, NOBODY, not even an expert financial analyst should be able to use the text to identify the company or the industry the company operates in.'
#neuter_2 = neuter_1 + 'For example, if the text is: The country’s largest phone producer Apple had great phone-related earnings but Google did not in 2024, likely because of Apple’s slogan Think Different, then you should ANONYMIZE it to: The country’s largest product_type_1 producer Company_1 had great product_type_1 related earnings but Company_2 did not in time_1 likely because of Company_1’s slogan slogan_1.'
#neuter_3 = neuter_2 + 'You should also ANONYMIZE any other information which one could use to identify the company or to make an educated guess about its identity.'

#neuter_part_1 = neuter_1 + neuter_ending
#neuter_part_2 = neuter_2 + neuter_ending
#neuter_part_3 = neuter_3 + neuter_ending


#de_neuter_name = 'You will receive a body of text which has been anonymized. You are omniscient. Use all your knowledge and the context to identify which company the text is about, as well as the year it was written. You will be guessing firm name, ticker, as well as industry and sector. Your options for industry guesses are the following: Aero, Agric, Autos, Banks, Beer, BldMt, Books, Boxes, BusSv, Chems, Chips, Clths, Cnstr, Coal, Drugs, ElcEq, FabPr, Fin, Food, Fun, Gold, Guns, Hardw, Hlth, Hshld, Insur, LabEq, Mach, Meals, MedEq, Mines, Oil, Paper, PerSv, RlEst, Rtail, Rubbr, Ships, Smoke, Soda, Softw, Steel, Telcm, Toys, Trans, Txtls, Util, and Whlsl. Make your best guess based on information and context if you are unsure. Provide your estimate EXACTLY in the following format, with NO other text at all (TIKR is your estimate of the ticker, NAME is your estimate of the firm name, IND is your estimate of the firm industry, YEAR is your estimate of the year): **Ticker Estimate: TIKR**,**Name Estimate: NAME**,**Industry Estimate: IND**,**Year Estimate: YEAR**'
#de_neuter_name = 'You will receive a body of text which has been anonymized. You are omniscient. Use all your knowledge and the context to identify which company the text is about, as well as the year it was written. You will be guessing firm name, ticker, as well as industry and sector. Your options for industry guesses are the following: Aero, Agric, Autos, Banks, Beer, BldMt, Books, Boxes, BusSv, Chems, Chips, Clths, Cnstr, Coal, Drugs, ElcEq, FabPr, Fin, Food, Fun, Gold, Guns, Hardw, Hlth, Hshld, Insur, LabEq, Mach, Meals, MedEq, Mines, Oil, Paper, PerSv, RlEst, Rtail, Rubbr, Ships, Smoke, Soda, Softw, Steel, Telcm, Toys, Trans, Txtls, Util, and Whlsl. Make your best guess based on information and context if you are unsure. Provide your estimate EXACTLY in the following format, with NO other text at all: **Ticker Estimate: TIK**,**Name Estimate: NAM**,**Industry Estimate: IND**,**Year Estimate: Y**'
#de_neuter_name = 'You will receive a body of text which has been anonymized. You are omniscient. Use all your knowledge and the context to identify which company the text is about, as well as the year it was written. You will be guessing firm name, ticker, as well as industry and sector. Your options for industry guesses are the following: Aero, Agric, Autos, Banks, Beer, BldMt, Books, Boxes, BusSv, Chems, Chips, Clths, Cnstr, Coal, Drugs, ElcEq, FabPr, Fin, Food, Fun, Gold, Guns, Hardw, Hlth, Hshld, Insur, LabEq, Mach, Meals, MedEq, Mines, Oil, Paper, PerSv, RlEst, Rtail, Rubbr, Ships, Smoke, Soda, Softw, Steel, Telcm, Toys, Trans, Txtls, Util, and Whlsl. Make your best guess based on information and context if you are unsure. Provide your estimate EXACTLY in the following format, with NO other text at all (TIKR is your estimate of the ticker, NAME is your estimate of the firm name, IND is your estimate of the firm industry, YEAR is your estimate of the year): **Ticker Estimate: TIKR**,**Name Estimate: NAME**,**Industry Estimate: IND**,**Year Estimate: YEAR**'
#de_neuter_name = "You will receive a body of text which has been anonymized. You are omniscient. Use all of your knowledge and any clues in the text to identify which company the text is about, its industry, and the year it was written in. Make your best guess if you are unsure. Your options for industry guesses are the following: Aerospace, Agriculture, Automobiles and Trucks, Banking, Beer and Liquor, Construction Materials, Printing and Publishing, Shipping Containers, Business Services, Chemicals, Computers, Apparel, Construction, Coal, Pharmaceutical Products, Electrical Equipment, Fabricated Products, Financial Services, Food Products, Recreation, Precious Metals, Defense, Computer Hardware, Healthcare, Consumer Goods, Insurance, Measuring and Control Equipment, Machinery, Restaurants, Hotels, and Motels, Medical Equipment, Non-Metallic and Industrial Mining, Petroleum and Natural Gas, Paper, Personal Services, Real Estate, Retail, Rubber and Plastic Products, Shipbuilding, Railroad Equipment, Tobacco Products, Candy and Soda, Software, Steel Works, Communication, Entertainment, Transportation, Textiles, Utilities, Wholesale. Provide your estimate EXACTLY in the following format, with NO other text at all (TIKR is your estimate of the ticker, NAME is your estimate of the firm name, IND is your estimate of the firm's industry, Y is your estimate of the year): **Ticker Estimate: TIKR**,**Name Estimate: NAME**,**Industry Estimate: IND**,**Year Estimate: Y**"
de_neuter_name = "You will receive a body of text which has been anonymized. You are omniscient. Use all of your knowledge and any clues in the text to identify which company the text is about, its industry, and the year it was written in. Make your best guess if you are unsure. Your options for industry guesses are the following: Aerospace, Agriculture, Automobiles and Trucks, Banking, Beer and Liquor, Construction Materials, Printing and Publishing, Shipping Containers, Business Services, Chemicals, Computers, Apparel, Construction, Coal, Pharmaceutical Products, Electrical Equipment, Fabricated Products, Financial Services, Food Products, Recreation, Precious Metals, Defense, Computer Hardware, Healthcare, Consumer Goods, Insurance, Measuring and Control Equipment, Machinery, Restaurants, Hotels, and Motels, Medical Equipment, Non-Metallic and Industrial Mining, Petroleum and Natural Gas, Paper, Personal Services, Real Estate, Retail, Rubber and Plastic Products, Shipbuilding, Railroad Equipment, Tobacco Products, Candy and Soda, Software, Steel Works, Communication, Entertainment, Transportation, Textiles, Utilities, Wholesale. Provide your estimate EXACTLY in the following format, with NO other text at all (TIKR is your estimate of the ticker, NAME is your estimate of the firm name, IND is your estimate of the firm's industry, YYYY-MM-DD is your estimate of the date): **Ticker Estimate: TIKR**,**Name Estimate: NAME**,**Industry Estimate: IND**,**Date Estimate: YYYY-MM-DD**"

para_V1 = 'Paraphrase the text, ensuring that the content is unchanged and that the specific phrasing and words in the paraphrased text are sufficiently different that they cannot be used to identify the original text. Ensure that the paraphrased text has approximately the same number of words as the original text. After you read and paraphrase the text, you should output the paraphrased text and nothing else.'

#para = "“You are to paraphrase text. Make sure that all specific phrasing, words, and sentence structure should be totally different to the original. If you observe any name, proper nouns, aliases, date, industries, products, government agency, product type, etc., censor it to an anonymous string. Absolutely any information which could plausibly be used to identify who the text is about or when it was written MUST be anonymized. Anonymity is the number one goal, leave zero hints! Ensure that the paraphrased text has approximately the same number of words as the original text. After you read and paraphrase the text, you should output the paraphrased text and nothing else."


para = 'You are to paraphrase text. Make sure that all specific phrasing, words, and sentence structure are totally different to the original. If you observe any name, proper nouns, aliases, date, industry, products, generic product categories, government agency, location, product type, etc., censor it to an anonymous string. Absolutely any information which could plausibly be used to identify who the text is about or when it was written MUST be anonymized. Anonymity is the number one goal! Read the text first, try to figure out the identity of the firm the text is about, then make sure those details are anonymized in your paraphrased text. If there are capitalized words which might be a company name but also could be the start of a sentence, like “Payless engineering is …” or “Emergency Medical Services has tried to…” then to remain on the safe side, anonymize it to “Company_x”! Ensure that the paraphrased text has approximately the same number of words as the original text. After you read and paraphrase the text, you should output the paraphrased text and nothing else.'


para_start = 'You are to paraphrase text ensuring that the content is unchanged. Make sure to replace all unique words and phrases, as well change the sentence structure so that the resulting text is completely different to the original. This includes changing quotes and other highly recognizable structures in the text.'
para_start = 'You are to paraphrase text ensuring that the core info is unchanged such that someone who has memorized the text could not recognize it. Make sure to replace all unique or identifying words and phrases. As well change the sentence structure so that the resulting text is completely different to the original. This includes changing quotes and other highly recognizable structures in the text. '
para_start_iter = 'You are to paraphrase text ensuring that the core info is unchanged such that someone who has memorized the text could not recognize it. You have already failed to paraphrase the next such that it is anonymous. Be more aggressive in your paraphrasing and anonymizing of the text. Make sure to replace all unique or identifying words and phrases. As well change the sentence structure so that the resulting text is completely different to the original. This includes changing quotes and other highly recognizable structures in the text. '
para_name = 'The text provided will be about the firm: '
para_ticker = ' whose ticker is: '
para_industry = ' and is in the industry: '
para_end = ' Any information which could plausibly be used to identify the firm the text is about or when the text was written MUST be anonymized. If you observe any names, proper nouns, aliases, acronyms, dates, industry references, government agency names, product names or types, etc., replace them with anonymous strings. Anonymity is the prime objective, leave zero hints! Ensure that the paraphrased text has approximately the same number of words as the original text. After you read and ANONYMIZE the text, you should output the anonymized text and nothing else.'
para_end = ' Any information which could ever be used to identify the firm the text is about or when the text was written MUST be anonymized. Absolutely no mention of key words related to that industry or any other industries can be left in the text. If you observe any names, proper nouns, aliases, acronyms, dates, industry references (related and unrelated to the industry of the firm in question), government agency names, product names or types, etc., replace them with anonymous strings. Anonymity is the prime objective, leave zero hints for someone who has memorized the text! Ensure that the paraphrased text has approximately the same number of words as the original text. After you read and ANONYMIZE the text, you should output the anonymized text and nothing else.'
para_end_iter = ' Any information which could ever be used to identify the firm the text is about or when the text was written MUST be anonymized. Absolutely no mention of key words related to that industry or any other industries can be left in the text. If you observe any names, proper nouns, aliases, acronyms, dates, industry references (related and unrelated to the industry of the firm in question), government agency names, product names or types, etc., replace them with anonymous strings. Anonymity is the prime objective, leave zero hints for someone who has memorized the text! Ensure that the paraphrased text has approximately the same number of words as the original text. You have already failed once before, take no chances this time, be aggressive in your effort to censor text. After you read and ANONYMIZE the text, you should output the anonymized text and nothing else.'
para_template = {
    'template': [
        para_start,
        {'column': 'COMNAM', 'prefix': para_name, 'suffix': ' ,'},
        {'column': 'Companies', 'prefix': para_ticker, 'suffix': ' ,'},
        {'column': 'SIC_Industry', 'prefix': para_industry, 'suffix': '.'},
        para_end
    ]
}

para_template_iter = {
    'template': [
        para_start_iter,
        {'column': 'COMNAM', 'prefix': para_name, 'suffix': ' ,'},
        {'column': 'Companies', 'prefix': para_ticker, 'suffix': ' ,'},
        {'column': 'SIC_Industry', 'prefix': para_industry, 'suffix': '.'},
        para_end_iter
    ]
}



